package com.ronan.heyboxlite

internal enum class ComposeCheckinRoute {
    CENTER,
    PAIRING,
    MOBILE_LOGIN,
    TASK_SETTINGS,
    MEMBERSHIP,
    CHECKOUT,
    REDEEM,
    PURCHASES,
    HISTORY,
    HISTORY_DETAIL,
}

internal enum class ComposeCheckinStage {
    UNPAIRED,
    SYNCING,
    CONNECTED,
    RUNNING,
    ERROR,
}

internal enum class ComposeCheckinStatusKind {
    NONE,
    NORMAL,
    ACCENT,
    ERROR,
}

internal data class ComposeCheckinUiState(
    val route: ComposeCheckinRoute = ComposeCheckinRoute.CENTER,
    val stage: ComposeCheckinStage = ComposeCheckinStage.UNPAIRED,
    val paired: Boolean = false,
    val supported: Boolean = true,
    val status: CheckinCenterClient.Status? = null,
    val history: CheckinHistory? = null,
    val historyLoading: Boolean = false,
    val historyError: String = "",
    val selectedHistoryEntry: CheckinHistory.Entry? = null,
    val errorMessage: String = "",
    val pairing: CheckinCenterClient.PairingStart? = null,
    val pairingRemainingSeconds: Long = 0L,
    val serviceMode: CheckinServiceAccountFlow.Mode = CheckinServiceAccountFlow.Mode.LOGIN,
    val serviceUsername: String = "",
    val servicePassword: String = "",
    val servicePasswordConfirmation: String = "",
    val serviceEmail: String = "",
    val serviceEmailCode: String = "",
    val serviceStatus: String = "",
    val serviceStatusKind: ComposeCheckinStatusKind = ComposeCheckinStatusKind.NONE,
    val serviceControlsEnabled: Boolean = true,
    val serviceEmailButton: String = "发送邮箱验证码",
    val serviceEmailButtonEnabled: Boolean = true,
    val recoveryEmail: String = "",
    val recoveryCode: String = "",
    val recoveryPassword: String = "",
    val recoveryPasswordConfirmation: String = "",
    val recoveryStatus: String = "",
    val recoveryStatusKind: ComposeCheckinStatusKind = ComposeCheckinStatusKind.NONE,
    val recoveryControlsEnabled: Boolean = true,
    val recoveryEmailButton: String = "发送邮箱验证码",
    val recoveryEmailButtonEnabled: Boolean = true,
    val recoveryCompleted: Boolean = false,
    val mobileMode: CheckinMobileLoginFlow.Mode = CheckinMobileLoginFlow.Mode.SMS,
    val mobilePhone: String = "",
    val mobileCode: String = "",
    val mobilePassword: String = "",
    val mobileStatus: String = "",
    val mobileStatusKind: ComposeCheckinStatusKind = ComposeCheckinStatusKind.NONE,
    val mobileControlsEnabled: Boolean = true,
    val mobileHasSession: Boolean = false,
    val mobileSmsButton: String = "发送验证码",
    val mobileSmsButtonEnabled: Boolean = true,
    val focusTarget: String = "",
    val taskSaving: Boolean = false,
    val membership: ComposeMembershipUiState = ComposeMembershipUiState(),
    val showRevokeConfirm: Boolean = false,
)
